import { createSlice } from "@reduxjs/toolkit";

// create a slice of state using the createSlice function from Redux Toolkit
export const counterSlice = createSlice({
// the name of the slice of state
  name: "counter", 
  initialState: {
    // the initial state of the slice
    value: 0 
  },
  reducers: {
    increment: state => {
      // increment the counter by 1
      state.value++; 
    },
    decrement: state => {
    // decrement the counter by 1
      state.value--; 
    },
    incrementByAmount: (state, action) => {
   // increment the counter by the amount passed in the action payload   
      state.value += action.payload; 
    }
  }
});

// export the action creators generated by createSlice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// export the reducer function generated by createSlice
export default counterSlice.reducer;
