//reducers.js
import { createSlice } from "@reduxjs/toolkit";

// create a slice of state using the createSlice function from Redux Toolkit
export const bankSlice = createSlice({
  name: "bank",
  initialState: {
    balance: 0,
  },
  reducers: {
    // Define the reducers to handle the different actions
    deposit: (state, action) => {
      state.balance += parseFloat(action.payload);
    },
    withdraw: (state, action) => {
      state.balance -= parseFloat(action.payload);
    },
    addInterest: (state, action) => {
      const interestRate = parseFloat(action.payload);
      const interestAmount = state.balance * (interestRate / 100);
      state.balance += interestAmount;
    },
    applyCharges: (state, action) => {
      const chargeAmount = parseFloat(action.payload);
      state.balance -= chargeAmount;
    },
  },
});

// Export the action creators generated by createSlice
export const { deposit, withdraw, addInterest, applyCharges } = bankSlice.actions;

// Export the reducer function generated by createSlice
export default bankSlice.reducer;